/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegisterRegisterRouteImport } from './routes/register/register'
import { Route as LoginLoginRouteImport } from './routes/login/login'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRegisterRoute = RegisterRegisterRouteImport.update({
  id: '/register/register',
  path: '/register/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginLoginRoute = LoginLoginRouteImport.update({
  id: '/login/login',
  path: '/login/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login/login': typeof LoginLoginRoute
  '/register/register': typeof RegisterRegisterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login/login': typeof LoginLoginRoute
  '/register/register': typeof RegisterRegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login/login': typeof LoginLoginRoute
  '/register/register': typeof RegisterRegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/login/login' | '/register/register'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/login/login' | '/register/register'
  id: '__root__' | '/' | '/dashboard' | '/login/login' | '/register/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginLoginRoute: typeof LoginLoginRoute
  RegisterRegisterRoute: typeof RegisterRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/register': {
      id: '/register/register'
      path: '/register/register'
      fullPath: '/register/register'
      preLoaderRoute: typeof RegisterRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/login': {
      id: '/login/login'
      path: '/login/login'
      fullPath: '/login/login'
      preLoaderRoute: typeof LoginLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginLoginRoute: LoginLoginRoute,
  RegisterRegisterRoute: RegisterRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
